db:
  hostname: "localhost"
  username: "drayff"
  password: "drayff"
  database: "etta"

text:
  not-in-whitelist: "Вы не в вайтлисте!"
  deleted-from-whitelist: "Вы были удалены из вайтлиста!"
  is-over: "Ваша проходка закончилась!"